# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Ecology
description:      'The science of how nature works'
url:              http://www.datacarpentry.org/Ecology-Course
baseurl:          /Ecology-Course
email:            kerkhoffa@kenyon.edu
feedbackurl:      
author:
  name:           'Drew Kerkhoff'
  url:            https://kerkhofflab.org

github:
  repo:           https://github.com/kerkhoffa/Ecology-Course
  #               Be sure the 'Issues' feature is activated in 'Settings'
